name: Cherry Pick PR
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to cherry-pick'
        required: true
      target_branch:
        description: 'Target branch'
        required: true

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: artyrian/cherry-pick@v1.0.1
        with:
          pr_number: ${{ github.event.inputs.pr_number }}
          target_branch: ${{ github.event.inputs.target_branch }}
